version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      
      - run: ./gradlew build
      - store_artifacts:
          path: ~/repo/target/cemailService-0.0.1-SNAPSHOT.jar
          destination: package
      - run: ./gradlew check
      - store_artifacts:
          path: ~/repo/target/site/jacoco
          destination: test-results/coverage

workflows:
  version: 2
  workflow:
    jobs:
    - build