version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      
      - run: ./gradlew build
      - run: ./gradlew check

workflows:
  version: 2
  workflow:
    jobs:
    - build